### ISSUE TITLE
freeradius module fails to run on RHEL7

### ISSUE THREAD

**Issue by stojmir** [privacyidea/FreeRADIUS#25]
https://github.com/privacyidea/FreeRADIUS/blob/e2dda2752a0b16ab5e7122bd19c2bdfb5b9268ed/privacyidea_radius.pm#L451

rlm_perl: Can't locate object method "new" via package "JSON::XS" at /usr/lib/privacyidea/privacyidea_radius.pm line 451.

**Comment by plettich** [comment]
Hi Ivan,
thanks for the PR, we should test this more carefully.

**Comment by cornelinux** [comment]
I am so sorry, but the implementation has worked in our tests. We should merge this more carefully and check, why in certain cases it would not work! 
@plettich Did you test this on Debian and Ubuntu?

**Comment by cornelinux** [comment]
The last packed version was 3.0dev1. So this code has not been released neither for RHEL nor for Ubuntu,  yet. Need to check implementation on *all* plattforms.

**Comment by stojmir** [comment]
Just to clarify, JSON::XS is not available under RHEL7.
On the other hand, I tried using JSON::PP and JSON instead and both of those worked fine.

**Comment by cornelinux** [comment]
We have the epel repository activated. I think you need it to activate anyways for certain other dependencies!?

In epel you will find ``perl-JSON-XS``.
However ofter discussing this a bit deeper it looks like it makes sense to use

~~~~perl
JSON->new...
~~~~

It might make sense to install perl-JSON-XS to speed things up or to simply have a maybe more robust C implementation instead of Perl. Currently I can not tell this.
Unfortunately to my knowledge there is no concept of *suggested* packages in rpm, so this can only be documented: "if you want to or can, install perl-JSON-XS".
@stojmir any thoughts on this?

**Comment by stojmir** [comment]
Yeah, probably a comment would be enough.
But also maybe worth checking if JSON vs JSON-XS actually makes any meaningful difference for such a basic use case.
If the performance gain is only a few milliseconds, then just stick with JSON as it is the more common and easily available package.

**Comment by stojmir** [comment]
OK, so I just did some quick tests and I could not see any noticeable difference in performance.
I also noticed however that the perl-JSON-XS depends on two additional EPEL packages (perl-Types-Serialiser and perl-common-sense), so from a usability perspective I think JSON->new is the winner over JSON::XS.
